### ISSUE TITLE
Issue with __rpow__

### ISSUE THREAD

**Issue by RenhaoL** [cs107-undefined/cs107-FinalProject#24]
test case: log(x*3 + tan(2*x), np.e) + 2**x 

raise error: 
Traceback (most recent call last):
  File "/Users/renhaoluo/Desktop/cs107-FinalProject/test/test_trace.py", line 38, in test_forward
    self.assertEqual(trace(self.f8, x = 3), (2.16, 0.59))
  File "./src/undefined/API.py", line 71, in trace
    f = f(**variables)
  File "/Users/renhaoluo/Desktop/cs107-FinalProject/test/test_trace.py", line 21, in <lambda>
    self.f8 = lambda x: log(x*3 + tan(2*x), np.e) + 2**x
  File "./src/undefined/UDFunction.py", line 351, in __rpow__
    return UDFunction(new_val, new_der)
UnboundLocalError: local variable 'new_der' referenced before assignment

**Comment by XinranTang** [comment]
solved
